# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     Metrics/BlockLength:
#       Enabled: true
#

# @NOTE: IgnoredMethods by default only contains "refine"
Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context
    - feature
    - scenario
