# Defaults for this cop are found here:
# https://github.com/rubocop/rubocop/blob/master/config/default.yml
#
# Add customizations below.
#
# Ensure to document why we change a default by linking the corresponding PR.
# For example:
#
#     Style/AndOr:
#       Reference: 'https://github.com/dbl-works/rubocop-dbl/pull/34'
#       Enabled: true
#

# @NOTE: changed from "always" to "never"
Style/FrozenStringLiteralComment:
  Reference: 'we have no reference for this change'
  EnforcedStyle: never

# enforces to use 'name'.to_sym over 'name'.intern and so on
Style/StringMethods:
  Reference: 'we have no reference for this change'
  Enabled: true

# @NOTE: changed from "compact" to "expanded"
Style/EmptyMethod:
  Reference: 'we have no reference for this change'
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

# @NOTE: allowed AllowMultipleReturnValues
Style/RedundantReturn:
  Reference: 'we have no reference for this change'
  Enabled: true
  AllowMultipleReturnValues: true

# @NOTE: allowed AllowAsExpressionSeparator
Style/Semicolon:
  Reference: 'we have no reference for this change'
  Enabled: true
  AllowAsExpressionSeparator: true

Style/CollectionMethods:
  Reference: 'we have no reference for this change'
  Enabled: true

Style/Documentation:
  Reference: 'we have no reference for this change'
  Enabled: false

# @NOTE: changed EnforcedStyleForMultiline from "no_comma" to "comma"
Style/TrailingCommaInArguments:
  Reference: 'we have no reference for this change'
  EnforcedStyleForMultiline: comma

# @NOTE: changed EnforcedStyleForMultiline from "no_comma" to "comma"
Style/TrailingCommaInArrayLiteral:
  Reference: 'we have no reference for this change'
  EnforcedStyleForMultiline: comma

# @NOTE: changed EnforcedStyleForMultiline from "no_comma" to "comma"
Style/TrailingCommaInHashLiteral:
  Reference: 'we have no reference for this change'
  EnforcedStyleForMultiline: comma

#
# @NOTE: the following cops are "pending" by default
#
Style/ArgumentsForwarding:
  Reference: 'we have no reference for this change'
  Enabled: false

Style/CollectionCompact:
  Reference: 'we have no reference for this change'
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Reference: 'we have no reference for this change'
  Enabled: true

Style/NegatedIfElseCondition:
  Reference: 'we have no reference for this change'
  Enabled: true

Style/NilLambda:
  Reference: 'we have no reference for this change'
  Enabled: true

Style/RedundantArgument:
  Reference: 'we have no reference for this change'
  Enabled: true

Style/SwapValues:
  Reference: 'we have no reference for this change'
  Enabled: true
