require:
  - rubocop-md
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-sorbet


inherit_from:
  - cops/layout.yml
  - cops/lint.yml
  - cops/metrics.yml
  - cops/naming.yml
  - cops/performance.yml
  - cops/rails.yml
  - cops/rspec.yml
  - cops/style.yml
  - cops/types.yml


# if you want to change the cache directory, simple set `RUBOCOP_CACHE_ROOT` for your local shell.
# see: https://docs.rubocop.org/rubocop/usage/caching.html
AllCops:
  UseCache: true
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
    # Additional exclude files by rubocop-rails
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
