require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails


inherit_from:
  - cops/layout.yml
  - cops/lint.yml
  - cops/metrics.yml
  - cops/naming.yml
  - cops/performance.yml
  - cops/rails.yml
  - cops/rspec.yml
  - cops/style.yml


AllCops:
  UseCache: true
  MaxFilesInCache: 5
  CacheRootDirectory: /tmp/**
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
    # Additional exclude files by rubocop-rails
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
